bookings/urls.py
from core.views import homeView, AboutView, ProfileView, bookingsView
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", homeView, name="home"),
    path("admin/", admin.site.urls),
    path("hotels/", include("core.urls")),
    path("accounts/", include("allauth.urls"), name="auth"),
    path("about/", AboutView.as_view(), name="about"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("bookings/", bookingsView, name="bookings"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.hotel_search_view, name="search"),
    path("<int:my_id>/", views.details_view, name="details"),
]

core/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
import numpy as np
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    address = models.CharField(max_length=100)
    longitude = models.FloatField()
    latitude = models.FloatField()
    smoking_rooms = models.BooleanField(default=False)
    pool = models.BooleanField(default=False)
    gym = models.BooleanField(default=False)
    room_service = models.BooleanField(default=False)
    spa = models.BooleanField(default=False)
    breakfast = models.BooleanField(default=False)
    free_wifi = models.BooleanField(default=False)
    dry_cleaning = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def average_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        if all_ratings:
            return round(np.mean(all_ratings))
        else:
            0

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return f"/hotels/{self.id}"

    def __str__(self):
        return self.name


class Photo(models.Model):
    url = models.CharField(max_length=400)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    rating = models.IntegerField(
        default=3,
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    review = models.TextField(default="Great", null=True)


class Booking(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    start = models.DateField()
    end = models.DateField()
    guests = models.IntegerField()
    total = models.IntegerField()
    payment = models.CharField(max_length=100)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)

    class Meta:
        ordering = ["start"]


class Profile(models.Model):
    """
    User profile model.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10, blank=True)
    profile_pic = models.ImageField(
        upload_to="profile_pics/", blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance=None, created=False, **kwargs):
    """
    Create a profile for the user when user is created.
    """
    if created:
        Profile.objects.create(user=instance)

core/forms.py
from email.policy import default
from random import choices
from django import forms

locations = [
    ("Kensington and Chelsea", "Kensington and Chelsea"),
    ("Westminster Borough", "Westminster Borough"),
    ("Central London", "Central London"),
    ("Camden", "Camden"),
    ("West End", "West End"),
    ("Kensington", "Kensington"),
    ("Hyde Park", "Hyde Park"),
    ("Tower Hamlets", "Tower Hamlets"),
    ("Wimbledon", "Wimbledon"),
    ("Wandsworth", "Wandsworth"),
    ("Newham", "Newham"),
    ("Lewisham", "Lewisham"),
    ("Clerkenwell", "Clerkenwell"),
    ("Stratford", "Stratford"),
    ("City of London", "City of London"),
    ("Shoreditch", "Shoreditch"),
    ("Canary Wharf and Docklands", "Canary Wharf and Docklands"),
    ("Regent's Park", "Regent's Park"),
    ("Spitalfields", "Spitalfields"),
    ("Hammersmith and Fulham", "Hammersmith and Fulham"),
    ("South Kensington", "South Kensington"),
    ("Paddington", "Paddington"),
    ("Oxford Street", "Oxford Street"),
    ("Wembley", "Wembley")
]

Ratings = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★")
)


class searchForm(forms.Form):
    rating = forms.IntegerField(required=False, min_value=1, max_value=5)
    neighbourhood = forms.ChoiceField(
        choices=locations, widget=forms.RadioSelect, required=False)
    price_lower = forms.IntegerField(required=False, min_value=0)
    price_upper = forms.IntegerField(required=False, min_value=1)
    smoking_rooms = forms.BooleanField(required=False)
    pool = forms.BooleanField(required=False)
    gym = forms.BooleanField(required=False)
    room_service = forms.BooleanField(required=False)
    spa = forms.BooleanField(required=False)
    breakfast = forms.BooleanField(required=False)
    free_wifi = forms.BooleanField(required=False)
    dry_cleaning = forms.BooleanField(required=False)


class RatingForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={"placeholder": "Enter your Name"}))
    review = forms.CharField(widget=forms.Textarea)
    rating = forms.ChoiceField(choices=Ratings)


class BookingForm(forms.Form):
    start = forms.DateField(widget=forms.SelectDateWidget, required=True)
    end = forms.DateField(widget=forms.SelectDateWidget, required=True)
    CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]
    guests = forms.ChoiceField(
        choices=CHOICES, required=True)
    total = forms.IntegerField(min_value=1, required=False)
    PAYMENT_CHOICES = (
        ("C", "Credit Card"),
        ("D", "Debit Card"),
        ("U", "UPI"),
        ("COD", "Cash On Delivery"),
    )
    payment = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={
            "class": "custom-control-label",
        }), choices=PAYMENT_CHOICES)


class ProfileForm(forms.Form):
    """Profile form"""
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    profile_pic = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=10, required=False)


class PasswordForm(forms.Form):
    """Password form"""
    password_old = forms.CharField(widget=forms.PasswordInput, required=False)
    password1 = forms.CharField(widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)

core/views.py
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.contrib import messages
from django.shortcuts import redirect, render

from .forms import RatingForm, searchForm, BookingForm, ProfileForm, PasswordForm
from .models import Hotel, Review, Booking, Profile
from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

# Create your views here.


def priceRange(price):
    diff = 1000
    h = Hotel.objects.all()
    h = h.filter(price__gt=price-diff)
    h = h.filter(price__lt=price+diff)
    return h[:4]


def searchFunctionality(smoking_rooms, pool, free_wifi, gym, spa, dry_cleaning, room_service, breakfast):
    x = Hotel.objects.all()
    x = x.filter(smoking_rooms=True) if smoking_rooms == True else x
    x = x.filter(pool=True) if pool == True else x
    x = x.filter(free_wifi=True) if free_wifi else x
    x = x.filter(gym=True) if gym else x
    x = x.filter(spa=True) if spa else x
    x = x.filter(dry_cleaning=True) if dry_cleaning else x
    x = x.filter(room_service=True) if room_service else x
    x = x.filter(breakfast=True) if breakfast else x
    return x


def homeView(request):
    context = {}
    return render(request, "home.html", context)


def bookingsView(request):
    bookings = Booking.objects.filter(user=request.user)
    context = {
        "bookings": bookings,
    }
    return render(request, "bookings.html", context)


def details_view(request, my_id):
    if request.method == "POST":
        form = RatingForm(request.POST or None)
        booking = BookingForm(request.POST or None)
        print(booking.errors)
        if booking.is_valid():
            user = request.user
            start = booking.cleaned_data["start"]
            end = booking.cleaned_data["end"]
            guests = booking.cleaned_data["guests"]
            payment = booking.cleaned_data["payment"]
            hotel = Hotel.objects.get(id=my_id)
            total = int(guests) * hotel.price
            book = Booking(
                start=start, end=end, guests=guests, payment=payment, total=total, hotel=hotel, user=user)
            book.save()
            return redirect("bookings")

        if form.is_valid():
            body = {
                "name": form.cleaned_data["name"],
                "rating": form.cleaned_data["rating"],
                "review": form.cleaned_data["review"]
            }
            rev = Review(rating=body["rating"], hotel=Hotel.objects.get(
                id=my_id), review=body["review"], user=request.user)
            rev.save()
            return redirect(f"/hotels/{my_id}")

    form = RatingForm()
    booking = BookingForm()
    h = Hotel.objects.get(id=my_id)
    similar = priceRange(h.price)
    photos = h.photo_set.all()
    reviews = h.review_set.all()
    photo_urls = [photo.url for photo in photos]
    facilities = [(h.smoking_rooms, "Smoking Rooms"), (h.pool, "Pool"), (h.gym, "Gymnasium"), (h.room_service, "Room Service"),
                  (h.spa, "Spa"), (h.breakfast, "Breakfast Included"), (h.free_wifi, "Free Wifi"), (h.dry_cleaning, "Dry Cleaning Service Offered")]
    context = {
        "reviews": reviews,
        "form": form,
        "object": h,
        "urls": photo_urls,
        "facilities": facilities,
        "recommendations": similar,
        "booking": booking
    }
    return render(request, "details.html", context)


def hotel_search_view(request):
    x = Hotel.objects.all()

    if request.method == "GET":
        form = searchForm(request.GET)
        # if the form is valid
        if form.is_valid():
            x = searchFunctionality(form.cleaned_data["smoking_rooms"], form.cleaned_data["pool"], form.cleaned_data["free_wifi"], form.cleaned_data["gym"],
                                    form.cleaned_data["spa"], form.cleaned_data["dry_cleaning"], form.cleaned_data["room_service"], form.cleaned_data["breakfast"])

            if form.cleaned_data["price_lower"] != None:
                x = x.filter(price__gt=form.cleaned_data["price_lower"])

            if form.cleaned_data["price_upper"] != None:
                x = x.filter(price__lt=form.cleaned_data["price_upper"])

            if form.cleaned_data["neighbourhood"] != None:
                x = x.filter(
                    address__icontains=form.cleaned_data["neighbourhood"])

            # if the rating field isn't filled
            if form.cleaned_data["rating"] != None:
                y = []
                # search every hotel and check if it has that rating. after this we get a list y with hotels of that rating
                for hotel in x:
                    # if the hotel has an average rating of what is asked
                    if hotel.review_set.all():
                        if hotel.average_rating() == form.cleaned_data["rating"]:
                            y.append(hotel)
                # x needs to be put into the context
                x = y

        context = {
            "hotels": x,
            "form": form
        }
        return render(request, "search.html", context)


class AboutView(TemplateView):
    """The About Page"""
    template_name = "about.html"


class ProfileView(LoginRequiredMixin, TemplateView):
    """
    Profile view.
    """
    template_name = "profile.html"

    def get(self, *args, **kwargs):
        """Get profile view."""
        user = self.request.user
        reviews = user.review_set.all()
        profile_form = ProfileForm()
        password_form = PasswordForm()
        profile = Profile.objects.get(user=self.request.user)
        return render(self.request, "profile.html", {"profile_form": profile_form, "password_form": password_form, "user": self.request.user, "profile": profile, "reviews": reviews})

    def post(self, *args, **kwargs):
        """Update profile view."""
        profile_form = ProfileForm(
            self.request.POST or None, self.request.FILES)
        password_form = PasswordForm(self.request.POST or None)
        user = self.request.user
        profile = Profile.objects.get(user=user)
        if profile_form.is_valid():
            print(profile_form.cleaned_data)
            user.first_name = profile_form.cleaned_data["first_name"]
            user.last_name = profile_form.cleaned_data["last_name"]
            try:
                testuser = get_user_model().objects.get(
                    username=profile_form.cleaned_data["username"])
                if testuser != user:
                    messages.warning(self.request, "Username already exists")
                    return redirect("core:profile")
            except ObjectDoesNotExist:
                user.username = profile_form.cleaned_data["username"]
            try:
                testuser = get_user_model().objects.get(
                    username=profile_form.cleaned_data["email"])
                if testuser != user:
                    messages.warning(self.request, "Email already exists")
                    return redirect("core:profile")
            except ObjectDoesNotExist:
                user.email = profile_form.cleaned_data["email"]
            profile.phone_number = profile_form.cleaned_data["phone_number"]
            if profile_form.cleaned_data["profile_pic"]:
                profile.profile_pic = profile_form.cleaned_data["profile_pic"]
            user.save()
            profile.save()
            messages.success(self.request, "Profile updated successfully")

        if password_form.is_valid():
            if password_form.cleaned_data["password1"] == "" and password_form.cleaned_data["password2"] == "" and password_form.cleaned_data["password_old"] == "":
                return redirect("profile")
            old_password = password_form.cleaned_data["password_old"]
            correct = user.check_password(old_password)
            if correct:
                try:
                    validate_password(
                        password_form.cleaned_data["password1"])
                except ValidationError:
                    messages.warning(
                        self.request, "Password does not pass validation checks.")
                    return redirect("profile")
                else:
                    if password_form.cleaned_data["password1"] == password_form.cleaned_data["password2"]:
                        user.set_password(
                            password_form.cleaned_data["password1"])
                        user.save()
                        messages.success(
                            self.request, "Password updated successfully!")
                    else:
                        messages.warning(
                            self.request, "Passwords do not match.")
                        return redirect("profile")
            else:
                messages.warning(self.request, "Old password is incorrect.")
        return redirect("profile")

core/templates/about.html
<!DOCTYPE html>
<html>

  <head>
    <title>Travel | About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
      }

      html {
        box-sizing: border-box;
      }

      *,
      *:before,
      *:after {
        box-sizing: inherit;
      }

      .column {
        float: left;
        width: 33.3%;
        margin-bottom: 16px;
        padding: 0 8px;
      }

      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: 8px;
      }

      .about-section {
        padding: 50px;
        text-align: center;
        background-color: #474e5d;
        color: white;
      }

      .container {
        padding: 0 16px;
      }

      .container::after,
      .row::after {
        content: "";
        clear: both;
        display: table;
      }

      .title {
        color: grey;
      }

      .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
      }

      .button:hover {
        background-color: #555;
      }

      @media screen and (max-width: 650px) {
        .column {
          width: 100%;
          display: block;
        }
      }
    </style>
  </head>

  <body>

    <div class="about-section">
      <h1>About Us</h1>
      <a href="/">
        <p>Travel.com</p>
      </a>
      <p>Great Britain's best travel website for backpackers.</p>
    </div>

    <h2 style="text-align:center">Our Team</h2>
    <div class="row">
      <div class="column">
        <div class="card">
          <div class="container">
            <h2>Adit Dhawan</h2>
            <p><button class="button">Contact</button></p>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="card">
          <div class="container">
            <h2>Paritosh Panda</h2>
            <p><button class="button">Contact</button></p>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="card">
          <div class="container">
            <h2>Shriman Visahan</h2>
            <p><button class="button">Contact</button></p>
          </div>
        </div>
      </div>

    </div>

  </body>

</html>

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Bootstrap v5.1.3-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block head %}{% endblock head %}
        <link rel="stylesheet" href="{% static "css/sticky_footer.css" %}">


        <!-- FontAwesome -->
        <script src="https://kit.fontawesome.com/6573a846cd.js" crossorigin="anonymous"></script>

    </head>

    <body class="bg-light">
        <div class="wrapper">
            <!-- Navbar -->
            {% include "partials/navbar.html" %}
            <!-- Body -->
            {% block body %}
            {% endblock body%}

            {% block content %}
            {% endblock content %}

            {% block extra_body %}
            {% endblock extra_body %}

            <!-- JS for Bootstrap v5.1.3 -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous">
            </script>

            <script>
                var elements = document.getElementsByClassName("btn-close");
                if (elements.length > 0) {
                    setTimeout(function () {
                        for (var i = 0; i < elements.length; i++) {
                            elements[i].click();
                        }
                    }, 3000)
                }
            </script>

            {% block scripts %}
            {% endblock scripts %}
        </div>
    </body>

</html>

core/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<title>Travel | Profile</title>
<link rel="stylesheet" href="{% static "css/profile.css" %}">
<style>
        .scrollable {
                height: 695px;
                overflow-y: scroll;
        }
</style>
{% endblock head %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
                <div class="col-md-3 border-right">
                        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                                <img class="rounded-circle mt-5" width="150px"
                                        src="{% if profile.profile_pic %}{{profile.profile_pic.url}}{% else %}https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg{% endif %}"><span
                                        class="font-weight-bold">
                                        {% if user.get_full_name %}
                                        {{user.get_full_name}}
                                        {% else %}
                                        {{user.username}}
                                        {% endif %}
                                </span>
                                <span class="text-black-50">{% if user.email %}{{user.email}}{% else %}Add your
                                        email{% endif %}</span><span>
                                </span><span class="mt-5"><a href="/bookings"
                                                class="btn btn-dark text-decoration-none">View
                                                your past
                                                bookings</a></span>
                        </div>
                </div>
                <div class="col-md-5 border-right">
                        <div class="p-3 py-5">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                        <h4 class="text-right">Profile Details</h4>
                                </div>
                                <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row mt-2">
                                                <div class="col-md-6"><label class="labels">Name</label><input
                                                                type="text" name="first_name" id="id_first_name"
                                                                class="form-control"
                                                                {% if user.first_name %}value="{{user.first_name}}"
                                                                {% else %} placeholder="Add first name" {% endif %}>
                                                </div>
                                                <div class="col-md-6"><label class="labels">Surname</label><input
                                                                type="text" name="last_name" id="id_last_name"
                                                                class="form-control"
                                                                {% if user.last_name %}value="{{user.last_name}}"
                                                                {% else %} placeholder="Add last name" {% endif %}>
                                                </div>
                                        </div>
                                        <div class="row mt-3">
                                                <div class="col-md-12"><label class="labels">Username</label><input
                                                                type="text" name="username" id="id_username"
                                                                class="form-control"
                                                                {% if user.username %}value="{{user.username}}"
                                                                {% else %} placeholder="Add username" {% endif %}></div>
                                                <div class="col-md-12"><label class="labels">Phone Number</label><input
                                                                type="text" name="phone_number" id="id_phone_number"
                                                                class="form-control"
                                                                {% if profile.phone_number %}value="{{profile.phone_number}}"
                                                                {% else %} placeholder="Enter phone number" {% endif %}>
                                                </div>
                                                <div class="col-md-12"><label class="labels">Email
                                                                ID</label><input type="text" name="email" id="id_email"
                                                                class="form-control" {% if user.email %}
                                                                value="{{user.email}}" {% else %}
                                                                placeholder="Enter email ID" {% endif %}>
                                                </div>
                                                <div class="col-md-12"><label class="labels">Profile
                                                                Picture</label><input type="file" name="profile_pic"
                                                                id="id_profile_pic" class="form-control"
                                                                accept="image/*">
                                                </div>
                                                <hr class="mt-3">
                                                <h5 class="mb-4">Change Password</h5>
                                                <div class="col-md-12"><label class="labels">Old Password</label><input
                                                                type="password" name="password_old" id="id_password_old"
                                                                class="form-control" placeholder="Enter old password">
                                                </div>
                                                <div class="col-md-12"><label class="labels">New Password</label><input
                                                                type="password" name="password1" id="id_password1"
                                                                class="form-control" placeholder="Enter new password">
                                                </div>
                                                <div class="col-md-12"><label class="labels">Confirm New
                                                                Password</label><input type="password" name="password2"
                                                                id="id_password2" class="form-control"
                                                                placeholder="Confirm new password">
                                                </div>
                                                <div class="mt-5 text-center"><button
                                                                class="btn btn-primary profile-button"
                                                                type="submit">Save
                                                                Profile</button>
                                                </div>
                                        </div>
                                </form>
                        </div>
                </div>
                <div class="col-md-4">
                        {% if reviews %}
                        <div class="p-3 py-5 scrollable">
                                {% else %}
                                <div class="p-3 py-5">
                                        {% endif %}

                                        <div class="d-flex justify-content-between align-items-center mb-3">
                                                <h4 class="text-right">Your Reviews</h4>
                                        </div>
                                        {% if reviews %}
                                        {% for review in reviews %}
                                        <div
                                                class="g-0 border rounded overflow-hidden flex-md-row mb-2 shadow-sm h-md-250 position-relative">
                                                <div class="p-4 d-flex flex-column position-static">
                                                        <strong class="d-inline-block mb-2
                                                                text-primary">Your Rating: {{review.rating}}
                                                                stars</strong>
                                                        <h5 class="mb-2">{{review.hotel.name}}</h5>
                                                        <div class="mb-1 text-muted">{{review.review }}
                                                        </div>
                                                </div>
                                        </div>
                                        {% endfor %}
                                        {% else %}
                                        <p>You don't have any reviews <yet!></yet!>
                                        </p>
                                        {% endif %}
                                </div>
                        </div>
                </div>
        </div>
</div>
</div>
{% include "partials/footer.html" %}

{% endblock content %}